# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:

# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

resources:
  pipelines:
  - pipeline: capatijohnpaul.Project1   # Name of the pipeline resource
    source: capatijohnpaul.MavenProject # Name of the triggering pipeline
    trigger: 
      branches:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: DownloadPipelineArtifact@2
#   inputs:
#     buildType: 'specific'
#     project: '0b5630f4-509c-4c1a-9c2d-9846b840a4ea'
#     definition: '5'
#     buildVersionToDownload: 'latest'
#     targetPath: '$(Pipeline.Workspace)'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '0b5630f4-509c-4c1a-9c2d-9846b840a4ea'
    pipeline: '5'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      
      SET PATH=packages\Tools.InnoSetup.6.0.3\tools
      $(System.ArtifactsDirectory)\demo\target\classes\iscc.bat

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
      **/target/*.exe
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'deploy'
    publishLocation: 'Container'